FROM node:14

# Create the working directory
RUN mkdir -p /app
WORKDIR /app

# Install required dependencies
COPY webapp/package.json /app/package.json
RUN npm install

# Copy the application code
COPY webapp /app

# Build the frontend client
RUN npm run build

# Set the working directory
WORKDIR /app/build

# Run the frontend client
CMD ["npm", "start"]
