FROM python:3.8

# Install necessary libraries
RUN pip install influxdb pandas

# Copy the Python script to the container
COPY processing/process_data.py /app/process_data.py

# Run the script when the container starts
CMD ["python", "/app/process_data.py"]
