FROM python:3.8

RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean

# Make a directory for our app
WORKDIR /consumer

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy our source code
COPY /api ./api

# Copy the wait-for-rabbitmq script
COPY consumer_entrypoint.sh .
RUN chmod +x consumer_entrypoint.sh

# Run the application
CMD ["./consumer_entrypoint.sh", "rabbitmqServer", "python", "-m", "api"]
